# Generated by Django 3.2.8 on 2021-10-06 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=9)),
                ('course_name', models.CharField(max_length=60)),
                ('section', models.CharField(blank=True, max_length=5)),
                ('credits', models.IntegerField()),
                ('schedule', models.CharField(blank=True, max_length=60)),
                ('classroom', models.CharField(blank=True, max_length=10)),
                ('professor', models.CharField(blank=True, max_length=60)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
